### ISSUE TITLE
Programs Functionalites

### ISSUE THREAD

**Issue by gargarchit** [ravi-saini35/Data_Structure#2]
Hey Ravindra,

Here You Can Add Your Programs Functionalities at the above of the programs in comments therefore contributor can easily understand what your program works

Thank You

**Comment by ravi-saini35** [comment]
Thanks, Archit for your kind attention. But I didn't get you properly, what kind of comments you are talking about here.
are you talking about comments in between codes?

**Comment by gargarchit** [comment]
Hey,

I mean you can mentain about what your programs works or like in your Stack.c program you can write Implementation to stack using Array or Linked List ,also what function you use like pop, push and what they are doing in some lines in comments

I hope you get it

**Comment by ravi-saini35** [comment]
Hey man;
thanks for your helping hand, to make my repository better.

**Comment by gargarchit** [comment]
yeah, ur Welcome
